# This workflow will do a clean install of node dependencies, build the source code, run tests across different versions of node and deploy
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and test

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 14.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Test server
        run: npm test
        continue-on-error: true
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          LOG_LEVEL: debug
      - name: Cat server test logs
        run: cat logs/test/app.log
      - name: Unit test client
        run: cd client && npm run test:unit
      - name: E2E test client
        run: npm run test:e2e
