name: Report code coverage

on:
  push:
    branches:
      - 'master'

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - name: Test coverage
        run: |
          npm run coverage
      - name: Report coverage
        run: |
          npm run report-coverage
      - name: Upload to codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
