# This workflow will do a clean install of node dependencies, build the source code, run tests across different versions of node and deploy
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NPM Audit

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 14.x

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v1.5.2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: vulnerability,test
      - uses: oke-py/npm-audit-action@v1.5.2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: vulnerability,test
          working_directory: "client"
